"""llm usage columns on assistant_event

Revision ID: 09d4b3edf433
Revises: df5ce4895036
Create Date: 2026-08-29 12:34:10.475934

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '09d4b3edf433'
down_revision: str | Sequence[str] | None = 'df5ce4895036'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_event', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.add_column('assistant_event', sa.Column('llm_model', sa.String(length=100), nullable=True))
    op.add_column('assistant_event', sa.Column('prompt_tokens', sa.Integer(), nullable=True))
    op.add_column('assistant_event', sa.Column('completion_tokens', sa.Integer(), nullable=True))
    op.add_column('assistant_event', sa.Column('llm_ms', sa.Integer(), nullable=True))
    op.add_column('assistant_event', sa.Column('cost_micros', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_event', 'cost_micros')
    op.drop_column('assistant_event', 'llm_ms')
    op.drop_column('assistant_event', 'completion_tokens')
    op.drop_column('assistant_event', 'prompt_tokens')
    op.drop_column('assistant_event', 'llm_model')
    op.drop_column('assistant_event', 'llm_provider')
    # ### end Alembic commands ###
