"""tenancy baseline

Revision ID: 4024383a2d62
Revises:
Create Date: 2026-08-29 11:07:57.189925

Tenancy tables for feature 002-backoffice-analytics (T104): Tenant + per-tenant adapter/LLM/
promo config, widget keys, and the admin/RBAC tables. Row-Level Security is enabled on every
tenant-scoped table as defense in depth alongside the mandatory `tenant_id` repository
argument (plan.md D1/T106-T107) — Postgres only; SQLite (the test-suite target) has no RLS,
so isolation there is enforced solely at the repository layer, which is what T107 tests.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4024383a2d62'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='adminuserstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_user'))
    )
    op.create_index(op.f('ix_admin_user_email'), 'admin_user', ['email'], unique=True)
    op.create_table('tenant',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', name='tenantstatus', native_enum=False), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant'))
    )
    op.create_index(op.f('ix_tenant_slug'), 'tenant', ['slug'], unique=True)
    op.create_table('admin_audit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=200), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_user.id'], name=op.f('fk_admin_audit_admin_user_id_admin_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_admin_audit_tenant_id_tenant'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_audit'))
    )
    op.create_index(op.f('ix_admin_audit_tenant_id'), 'admin_audit', ['tenant_id'], unique=False)
    op.create_table('tenant_adapter_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('host_header', sa.String(length=255), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('default_customer_id', sa.String(length=50), nullable=True),
    sa.Column('default_address_id', sa.String(length=50), nullable=True),
    sa.Column('default_carrier_id', sa.String(length=50), nullable=True),
    sa.Column('default_currency_id', sa.String(length=50), nullable=True),
    sa.Column('default_order_state_id', sa.String(length=50), nullable=True),
    sa.Column('payment_module', sa.String(length=100), nullable=True),
    sa.Column('payment_label', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_adapter_config_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_adapter_config')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_adapter_config_tenant_id'))
    )
    op.create_table('tenant_llm_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('monthly_token_budget', sa.BigInteger(), nullable=True),
    sa.Column('budget_action', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_llm_config_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_llm_config')),
    sa.UniqueConstraint('tenant_id', name=op.f('uq_tenant_llm_config_tenant_id'))
    )
    op.create_table('tenant_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_user_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'SUPPORT', name='adminrole', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_user.id'], name=op.f('fk_tenant_membership_admin_user_id_admin_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_membership_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_membership')),
    sa.UniqueConstraint('admin_user_id', 'tenant_id', name='uq_tenant_membership_user_tenant')
    )
    op.create_index(op.f('ix_tenant_membership_admin_user_id'), 'tenant_membership', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_tenant_membership_tenant_id'), 'tenant_membership', ['tenant_id'], unique=False)
    op.create_table('tenant_promo_rule',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('rule_id', sa.String(length=100), nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=False),
    sa.Column('target_code', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stackable_with', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_tenant_promo_rule_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_promo_rule')),
    sa.UniqueConstraint('tenant_id', 'rule_id', name='uq_tenant_promo_rule_tenant_rule')
    )
    op.create_index(op.f('ix_tenant_promo_rule_tenant_id'), 'tenant_promo_rule', ['tenant_id'], unique=False)
    op.create_table('widget_key',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('public_key', sa.String(length=80), nullable=False),
    sa.Column('allowed_origins', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], name=op.f('fk_widget_key_tenant_id_tenant'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_widget_key'))
    )
    op.create_index(op.f('ix_widget_key_public_key'), 'widget_key', ['public_key'], unique=True)
    op.create_index(op.f('ix_widget_key_tenant_id'), 'widget_key', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    _enable_row_level_security()


# Tenant-scoped tables: RLS policies compare against the session-local
# `app.current_tenant_id` GUC, set per-request by src/db/tenant_context.py via
# `SET LOCAL app.current_tenant_id = '<uuid>'`. A connection that never sets it (a bug, not
# the normal path) sees zero rows rather than every tenant's — fail closed.
_TENANT_SCOPED_TABLES = [
    "tenant_adapter_config",
    "tenant_llm_config",
    "tenant_promo_rule",
    "widget_key",
    "tenant_membership",
]


def _enable_row_level_security() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for table in _TENANT_SCOPED_TABLES:
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table}" '
            f"USING (tenant_id::text = current_setting('app.current_tenant_id', true))"
        )


def _disable_row_level_security() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    for table in _TENANT_SCOPED_TABLES:
        op.execute(f'DROP POLICY IF EXISTS tenant_isolation ON "{table}"')


def downgrade() -> None:
    """Downgrade schema."""
    _disable_row_level_security()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_key_tenant_id'), table_name='widget_key')
    op.drop_index(op.f('ix_widget_key_public_key'), table_name='widget_key')
    op.drop_table('widget_key')
    op.drop_index(op.f('ix_tenant_promo_rule_tenant_id'), table_name='tenant_promo_rule')
    op.drop_table('tenant_promo_rule')
    op.drop_index(op.f('ix_tenant_membership_tenant_id'), table_name='tenant_membership')
    op.drop_index(op.f('ix_tenant_membership_admin_user_id'), table_name='tenant_membership')
    op.drop_table('tenant_membership')
    op.drop_table('tenant_llm_config')
    op.drop_table('tenant_adapter_config')
    op.drop_index(op.f('ix_admin_audit_tenant_id'), table_name='admin_audit')
    op.drop_table('admin_audit')
    op.drop_index(op.f('ix_tenant_slug'), table_name='tenant')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_admin_user_email'), table_name='admin_user')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
