"""assistant event stream

Revision ID: df5ce4895036
Revises: 4024383a2d62
Create Date: 2026-08-29 11:30:39.544657

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df5ce4895036'
down_revision: str | Sequence[str] | None = '4024383a2d62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_event',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('turn_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('turn_elapsed_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_assistant_event'))
    )
    op.create_index(op.f('ix_assistant_event_session_id'), 'assistant_event', ['session_id'], unique=False)
    op.create_index('ix_assistant_event_session_seq', 'assistant_event', ['tenant_id', 'session_id', 'turn_id', 'seq'], unique=False)
    op.create_index(op.f('ix_assistant_event_tenant_id'), 'assistant_event', ['tenant_id'], unique=False)
    op.create_index('ix_assistant_event_tenant_occurred', 'assistant_event', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_assistant_event_turn_id'), 'assistant_event', ['turn_id'], unique=False)
    op.create_table('conversation_session',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.String(length=200), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('cart_id', sa.String(length=200), nullable=True),
    sa.Column('order_id', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_session')),
    sa.UniqueConstraint('tenant_id', 'session_id', name='uq_conversation_session_tenant_session')
    )
    op.create_index(op.f('ix_conversation_session_tenant_id'), 'conversation_session', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_session_tenant_id'), table_name='conversation_session')
    op.drop_table('conversation_session')
    op.drop_index(op.f('ix_assistant_event_turn_id'), table_name='assistant_event')
    op.drop_index('ix_assistant_event_tenant_occurred', table_name='assistant_event')
    op.drop_index(op.f('ix_assistant_event_tenant_id'), table_name='assistant_event')
    op.drop_index('ix_assistant_event_session_seq', table_name='assistant_event')
    op.drop_index(op.f('ix_assistant_event_session_id'), table_name='assistant_event')
    op.drop_table('assistant_event')
    # ### end Alembic commands ###
